sessions:
  # 上海期货交易所
  - exchange: SHFE
    instrument_prefix: "au"  # 黄金
    day: "09:00-15:00"
    night: "21:00-02:30"
  - exchange: SHFE
    instrument_prefix: "ag"  # 白银
    day: "09:00-15:00"
    night: "21:00-02:30"
  - exchange: SHFE
    instrument_prefix: "cu"  # 铜
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "al"  # 铝
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "zn"  # 锌
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "pb"  # 铅
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "ni"  # 镍
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "sn"  # 锡
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "ss"  # 不锈钢
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "ao"  # 氧化铝
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: SHFE
    instrument_prefix: "rb"  # 螺纹钢
    day: "09:00-15:00"
    night: "21:00-23:00"
  - exchange: SHFE
    instrument_prefix: "hc"  # 热轧卷板
    day: "09:00-15:00"
    night: "21:00-23:00"
  - exchange: SHFE
    instrument_prefix: "wr"  # 线材
    day: "09:00-15:00"
    night: "21:00-23:00"
  - exchange: SHFE
    instrument_prefix: "sp"  # 纸浆
    day: "09:00-15:00"
    night: "21:00-23:00"
  - exchange: SHFE
    instrument_prefix: "ru"  # 天然橡胶
    day: "09:00-15:00"
    night: "21:00-23:00"
  - exchange: SHFE
    instrument_prefix: "bu"  # 石油沥青
    day: "09:00-15:00"
    night: "21:00-23:00"
  - exchange: SHFE
    instrument_prefix: "fu"  # 燃料油
    day: "09:00-15:00"
    night: "21:00-23:00"

  # 上海国际能源中心
  - exchange: INE
    instrument_prefix: "sc"  # 原油
    day: "09:00-15:00"
    night: "21:00-02:30"
  - exchange: INE
    instrument_prefix: "bc"  # 国际铜
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: INE
    instrument_prefix: "lu"  # 低硫燃料油
    day: "09:00-15:00"
    night: "21:00-01:00"
  - exchange: INE
    instrument_prefix: "nr"  # 20号胶
    day: "09:00-15:00"
    night: "21:00-01:00"

  # 大连商品交易所（统一夜盘至23:00）
  - exchange: DCE
    day: "09:00-15:00"
    night: "21:00-23:00"

  # 郑州商品交易所（统一夜盘至23:00）
  - exchange: CZCE
    day: "09:00-15:00"
    night: "21:00-23:00"

  # 广州期货交易所
  - exchange: GFEX
    instrument_prefix: "si"  # 工业硅（无夜盘）
    day: "09:00-15:00"
    night: null
  - exchange: GFEX
    instrument_prefix: "lc"  # 碳酸锂（有夜盘）
    day: "09:00-15:00"
    night: "21:00-23:00"

  # 中国金融期货交易所
  - exchange: CFFEX
    instrument_prefix: "IF"  # 沪深300股指
    day: "09:30-15:00"
    night: null
  - exchange: CFFEX
    instrument_prefix: "IH"  # 上证50股指
    day: "09:30-15:00"
    night: null
  - exchange: CFFEX
    instrument_prefix: "IC"  # 中证500股指
    day: "09:30-15:00"
    night: null
  - exchange: CFFEX
    instrument_prefix: "IM"  # 中证1000股指
    day: "09:30-15:00"
    night: null
  - exchange: CFFEX
    instrument_prefix: "T"   # 10年期国债
    day: "09:30-15:15"
    night: null
  - exchange: CFFEX
    instrument_prefix: "TF"  # 5年期国债
    day: "09:30-15:15"
    night: null
  - exchange: CFFEX
    instrument_prefix: "TS"  # 2年期国债
    day: "09:30-15:15"
    night: null
  - exchange: CFFEX
    instrument_prefix: "TL"  # 30年期国债
    day: "09:30-15:15"
    night: null